version: "3.7"

services:
    # app
    app:
        volumes:
            - ./:/var/www
            - ./docker/supervisor/supervisord.php.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    # nginx
    nginx:
        ports:
            - "80:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/local/:/etc/nginx/conf.d/

    # # nodeJs
    # nodejs:
    #     container_name: ${APP_PROJECT_NAME}-nodejs
    #     build:
    #         args:
    #             user: '${WWWUSER}'
    #             uid: '${WWWGROUP}'
    #         context: ./docker/node
    #         dockerfile: Dockerfile
    #     image: nodejs
    #     tty: true
    #     restart: unless-stopped
    #     working_dir: /var/www/
    #     volumes:
    #         - ./:/var/www
    #     depends_on: 
    #         - app
    #     networks: 
    #         - app
    #         - proxy
