version: "3.7"

networks:
  app:
    name: ${APP_PROJECT_NAME}

  proxy:
    external: true

services:
    php:
        container_name: ${APP_PROJECT_NAME}-app
        build:
            context: .
            dockerfile: ./sail_client/php/Dockerfile
        image: ${APP_PROJECT_NAME}-app:local
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./sail_client/supervisor/supervisord.php.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - app
            - proxy

    nginx:
        container_name: ${APP_PROJECT_NAME}-nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes: 
            - ./:/var/www
            - ./sail_client/nginx/local/:/etc/nginx/conf.d/
        networks: 
            - app
            - proxy

    nodejs:
        container_name: ${APP_PROJECT_NAME}-nodejs
        build:
            context: .
            dockerfile: ./sail_client/node/Dockerfile
        image: ${APP_PROJECT_NAME}-node:local
        tty: true
        restart: unless-stopped
        # ports:
        #     - "80:5173"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - app
            - proxy
