version: "3.7"

services:
    app:
        container_name: ${APP_PROJECT_NAME}-app
        build:
            args:
                user: '${WWWUSER}'
                uid: '${WWWGROUP}'
            context: .
            dockerfile: ./sail_client/php/Dockerfile_prod
        image: ${APP_PROJECT_NAME}-php:prod
        restart: unless-stopped
        depends_on: 
            - mariadb
            - redis
        networks:
            - app
            - proxy

    worker:
        container_name: ${APP_PROJECT_NAME}-worker
        image: ${APP_PROJECT_NAME}-php:prod
        restart: unless-stopped
        working_dir: /var/www/
        depends_on: 
            - mariadb
            - redis
        networks: 
            - app
            - proxy