version: "3.7"

networks:
  app:
    name: ${APP_PROJECT_NAME}

  proxy:
    external: true

services:
    app:
        container_name: ${APP_PROJECT_NAME}-app
        build:
            args:
                WWWGROUP: '${WWWGROUP}'
            context: .
            dockerfile: ./sail_client/php/Dockerfile_local
        image: ${APP_PROJECT_NAME}-php:local
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./sail_client/supervisor/supervisord.php.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./sail_client/php/local/php.local.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app
            - proxy

    nginx:
        container_name: ${APP_PROJECT_NAME}-nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes: 
            - ./:/var/www
            - ./sail_client/nginx/local/:/etc/nginx/conf.d/
        networks: 
            - app
            - proxy

    # nodejs:
    #     container_name: ${APP_PROJECT_NAME}-nodejs
    #     build:
    #         args:
    #             user: '${WWWUSER}'
    #             uid: '${WWWGROUP}'
    #         context: ./sail_client/node
    #         dockerfile: Dockerfile
    #     image: nodejs
    #     tty: true
    #     restart: unless-stopped
    #     ports:
    #         - "80:5173"
    #     working_dir: /var/www/
    #     volumes:
    #         - ./:/var/www
    #     depends_on: 
    #         - app
    #     networks: 
    #         - app
    #         - proxy

