version: "3.7"

networks:
  app:
    name: ${APP_PROJECT_NAME}

  proxy:
    external: true

services:
    php:
        container_name: ${APP_PROJECT_NAME}-php
        build:
            context: .
            dockerfile: ./sail_client/php/Dockerfile_prod
        image: ${APP_PROJECT_NAME}-php:prod
        restart: unless-stopped
        depends_on: 
            - mariadb
            - redis
        networks:
            - app
            - proxy
