#!/bin/sh

fullPath=$(readlink -f "${BASH_SOURCE:-$0}")
path=$(dirname $fullPath)

createFile() {
    echo "#!/bin/sh" > /usr/local/bin/$1
    echo "sail $1 \$@" >> /usr/local/bin/$1
    chmod +x /usr/local/bin/$1
}

# sail
chmod +x ./bin/sail.sh
ln -s $path/bin/sail.sh /usr/local/bin/sail

# caddy (proxy)
createFile caddy

# composer
createFile composer

# node
createFile node

# npm
createFile npm

# php
createFile php

# bun
createFile bun

# npx
createFile npx

# yarn
createFile yarn
