version: "3.7"

services:

  mariadb:
    container_name: mariadb
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Psswd#123"
      MYSQL_ROOT_HOST: "%"
      # MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_USER: 'db_user'
      # MYSQL_PASSWORD: "Psswd#123"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
        - sail-mariadb:/var/lib/mysql
    networks: 
      - proxy
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

  redis:
    container_name: redis
    image: redis:latest
    volumes: 
      - sail-redis:/data
    networks: 
      - proxy

  mysql:
    container_name: mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Psswd#123"
      MYSQL_ROOT_HOST: "%"
      # MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - proxy

  pgsql:
    container_name: postgres
    image: 'postgres:15'
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: "Psswd#123"
      # POSTGRES_DB: '${DB_DATABASE}'
      # POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: "Psswd#123"
    volumes:
      - sail-pgsql:/var/lib/postgresql/data
    networks:
      - proxy

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: "Psswd#123"
        MSSQL_PID: 'Express'
    ports:
      - 1433:1433
    volumes:
      - sail-sqlserver:/var/opt/mssql
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  sail-redis:
  sail-mysql:
  sail-mariadb:
  sail-pgsql:
  sail-sqlserver:
