#!/bin/sh

# sail
rm -f /usr/local/bin/sail

# caddy (proxy)
rm -f /usr/local/bin/caddy

# composer
rm -f /usr/local/bin/composer

# node
rm -f /usr/local/bin/node

# npm
rm -f /usr/local/bin/npm

# php
rm -f /usr/local/bin/php

# bun
rm -f /usr/local/bin/bun

# npx
rm -f /usr/local/bin/npx

# yarn
rm -f /usr/local/bin/yarn

