#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

set -e

cp ./sail_client/php/local/env.local .env

cd storage
mkdir -p logs
mkdir -p framework
mkdir -p framework/cache
mkdir -p framework/cache/data
mkdir -p framework/sessions
mkdir -p framework/testing
mkdir -p framework/views
cd ..

# php artisan optimize

echo "-----------------------"
echo "-----------------------"
echo "INSTALAÇÃO FINALIZADA."
echo "-----------------------"
echo "-----------------------"

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
