ARG PHP=php74
ARG POSTGRES_VERSION=13

FROM sail:$php as phpPROD

ARG WWWGROUP

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set working directory
WORKDIR /var/www

COPY --chown=sail:sail . ./

# RUN --mount=type=cache,target=/tmp/cache composer install \
#         --ignore-platform-reqs \
#         --no-interaction \
#         --no-dev \
#         --no-plugins \
#         --no-scripts \
#         --no-autoloader \
#         --prefer-dist

#RUN rm -Rf /var/www/bootstrap/cache/services.php /var/www/bootstrap/cache/packages.php
RUN /usr/bin/composer dump-autoload --optimize --classmap-authoritative
