FROM php:7.4-fpm as php_local

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    supervisor \
    procps

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Microsoft SQL Server Prerequisites
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
#Debian 11
RUN curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18

# optional: for bcp and sqlcmd
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools18
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
RUN bash ~/.bashrc

# optional: kerberos library for debian-slim distributions
RUN apt-get install -y libgssapi-krb5-2

# Install PHP extensions
RUN docker-php-ext-install mbstring exif pdo_mysql gd sockets bcmath soap 

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Install redis
RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

# Install star-container
COPY ./sail_client/php/local/start-container /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

# Copy php config install
COPY ./sail_client/php/local/php.local.ini /usr/local/etc/php/conf.d/php.ini

# Set working directory
WORKDIR /var/www

# Expose port 9000
EXPOSE 9000

USER $user

ENTRYPOINT ["start-container"]
