FROM ubuntu:20.04

ARG user=sail
ARG WWWGROUP
ARG PHP=php7.4
ARG POSTGRES_VERSION=13

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y \
    gnupg \
    gosu \
    curl \
    wget \
    ca-certificates \
    zip \
    unzip \
    git \
    supervisor \
    sqlite3 \
    libcap2-bin \
    libpng-dev \
    python2 \
    dnsutils 

RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php

RUN apt update 
RUN apt install -y \
    $PHP-fpm \
    $PHP-common $PHP-cli $PHP-dev \
    $PHP-zip $PHP-xdebug \
    $PHP-memcached \
    $PHP-bz2 $PHP-imap $PHP-gd $PHP-imagick\
    $PHP-mbstring $PHP-intl $PHP-xml $PHP-bcmath $PHP-pcov \
    $PHP-curl $PHP-soap $PHP-ldap \
    $PHP-readline $PHP-msgpack $PHP-igbinary \
    $PHP-redis \
    $PHP-mysql $PHP-pgsql $PHP-sqlite3

# Install postgresql repository
RUN curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /usr/share/keyrings/pgdg.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# Install database clients
RUN apt-get update 
RUN apt-get install -y mysql-client 
RUN apt-get install -y postgresql-client-$POSTGRES_VERSION 

# Clear cache
RUN apt-get -y autoremove 
RUN apt-get clean 
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail

# Create system user to run Composer and Artisan Commands
# RUN useradd -G www-data,root -u $WWWGROUP -d /home/$user $user
# RUN mkdir -p /home/$user/.composer && \
#     chown -R $user:$user /home/$user

# Install star-container
COPY ./sail_client/php/local/start-container /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

# Copy php config install
COPY ./sail_client/php/local/php.local.ini /etc/php/7.4/fpm/php.ini

# RUN mkdir /run/php
# RUN chown sail:sail /run/php
# RUN chmod 777 /var/log
# RUN chmod 777 /run/php

#/php7.4-fpm.sock
#/php7.4-fpm.log

# Set working directory
WORKDIR /var/www

# Expose port 9000
EXPOSE 9000

# USER sail

ENTRYPOINT ["start-container"]