FROM node:14 as node

ARG WWWGROUP

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Create system user to run Node Commands
RUN useradd -G node,root -d /home/sail sail
RUN mkdir -p /home/sail && \
    chown -R sail:sail /home/sail && \
    chmod 777 /home/sail

# Set working directory
WORKDIR /var/www

USER sail
