FROM ubuntu:22.04 as php82

ARG DEBIAN_FRONTEND=noninteractive

ARG WWWGROUP

# Set a default conf for apt-get install
RUN echo 'apt::install-recommends "false";' > /etc/apt/apt.conf.d/no-install-recommends

# Install a few required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
        supervisor \
        curl \
        gnupg2 \
        software-properties-common && \
    add-apt-repository ppa:ondrej/php --yes 

# Update, upgrade
RUN apt-get update -qq -y && \
    apt-get upgrade -qq -y

# Packages
RUN apt-get install -qq -y \
    # Calling fpm locally
    libfcgi-bin \
    # Manipulate iptables rules (example: block smtps)
    iptables \
    # php8.2-cgi \
    # php8.2-dba \
    # php8.2-dev \
    # php8.2-enchant \
    # php8.2-phpdbg \
    # php8.2-pspell \
    # php8.2-recode \
    # php8.2-snmp \
    # php8.2-sybase \
    # php8.2-tidy \
    php8.2-apcu \
    php8.2-bcmath \
    php8.2-bz2 \
    php8.2-cli \
    php8.2-curl \
    php8.2-fpm \
    php8.2-gd \
    # php8.2-geoip \
    php8.2-gmp \
    php8.2-imagick \
    php8.2-imap \
    php8.2-interbase \
    php8.2-intl \
    # php8.2-json \
    php8.2-ldap \
    php8.2-mbstring \
    php8.2-mcrypt \
    php8.2-memcache \
    php8.2-memcached \
    php8.2-mongodb \
    php8.2-mysql \
    php8.2-odbc \
    php8.2-opcache \
    php8.2-pgsql \
    php8.2-readline \
    php8.2-redis \
    php8.2-soap \
    php8.2-sqlite3 \
    php8.2-ssh2 \
    php8.2-xdebug \
    php8.2-xhprof \
    php8.2-xml \
    php8.2-xmlrpc \
    php8.2-zip

 # Set a symlink to simplify the configuration, as we use a single php version
RUN ln -s /etc/php/8.2 /etc/php/current

# Log to stdout
RUN sed -i 's/^error_log.*/error_log = \/proc\/self\/fd\/2/g' /etc/php/current/fpm/php-fpm.conf && \
    echo 'access.log = /proc/self/fd/2' >> /etc/php/current/fpm/php-fpm.conf && \
    # Create log dir
    mkdir /var/log/php

# Clean
RUN apt-get autoremove -qq -y && \
    apt-get autoclean -qq && \
    apt-get clean -qq && \
    # Empty some directories from all files and hidden files
    rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
    find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete

# Copy custom php files
COPY ./common/php.dev.ini /etc/php/current/cli/conf.d/30-custom-php.ini
COPY ./common/php-fpm.ini /etc/php/current/fpm/conf.d/30-custom-php.ini
COPY ./common/www.conf /etc/php/current/fpm/pool.d/

# For custom Configuration that comes from outside (via a docker compose mount)
RUN mkdir /etc/php/current/fpm/user-conf.d && \
    echo "; Default empty file" > /etc/php/current/fpm/user-conf.d/example.conf && \
    # Create home for www-data
    mkdir /home/www-data && \
    chown www-data:www-data /home/www-data && \
    usermod -d /home/www-data www-data && \
    mkdir -p /run/php && \
    chown www-data:www-data /run/php

# Prepere entrypoint
COPY ./scripts/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data -u $WWWGROUP -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail

# Set working directory
WORKDIR /var/www

EXPOSE 9000

ENTRYPOINT  ["/docker-entrypoint.sh"]
