FROM sail:php80 as php80_sqlsrv

ARG  ACCEPT_EULA=Y
ARG  DEBIAN_FRONTEND=noninteractive

RUN curl -sSLo /etc/apt/trusted.gpg.d/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc && \
    echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod/ jammy main" > /etc/apt/sources.list.d/mssql.list && \
    apt-get update -qq && \
    ACCEPT_EULA=Y apt-get install -qq -y \
    # To keep
    mssql-tools unixodbc php8.0-sybase \
    # remove later
    unixodbc-dev php-pear php8.0-dev \
    gcc g++ build-essential && \
    # sqlsrv from PECL
    pecl channel-update pecl.php.net && \
    # Compile
    pecl -q install sqlsrv pdo_sqlsrv && \
    # Activate
    echo "extension=pdo_sqlsrv.so" > /etc/php/current/mods-available/pdo_sqlsrv.ini && \
    echo "extension=sqlsrv.so" > /etc/php/current/mods-available/sqlsrv.ini && \
    phpenmod pdo_sqlsrv sqlsrv && \
    # Remove useless packages / files
    pear clear-cache && \
    # Clean
    apt-get autoremove -qq -y && \
    apt-get autoclean -qq && \
    apt-get clean -qq && \
    # Empty some directories from all files and hidden files
    rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
    find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete