FROM ubuntu:22.04 as php81

ARG DEBIAN_FRONTEND=noninteractive

ARG WWWGROUP

# Set a default conf for apt-get install
RUN echo 'apt::install-recommends "false";' > /etc/apt/apt.conf.d/no-install-recommends

# Install a few required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
    supervisor \
    curl \
    gnupg2 \
    software-properties-common && \
    add-apt-repository ppa:ondrej/php --yes 

# Update, upgrade
RUN apt-get update -qq -y && \
    apt-get upgrade -qq -y

# Packages
RUN apt-get install -qq -y \
    # Calling fpm locally
    libfcgi-bin \
    # Manipulate iptables rules (example: block smtps)
    iptables \
    # php8.1-cgi \
    # php8.1-dba \
    # php8.1-dev \
    # php8.1-enchant \
    # php8.1-phpdbg \
    # php8.1-pspell \
    # php8.1-recode \
    # php8.1-snmp \
    # php8.1-sybase \
    # php8.1-tidy \
    php8.1-apcu \
    php8.1-bcmath \
    php8.1-bz2 \
    php8.1-cli \
    php8.1-curl \
    php8.1-fpm \
    php8.1-gd \
    # php8.1-geoip \
    php8.1-gmp \
    php8.1-imagick \
    php8.1-imap \
    php8.1-interbase \
    php8.1-intl \
    # php8.1-json \
    php8.1-ldap \
    php8.1-mbstring \
    php8.1-mcrypt \
    php8.1-memcache \
    php8.1-memcached \
    php8.1-mongodb \
    php8.1-mysql \
    php8.1-odbc \
    php8.1-opcache \
    php8.1-pgsql \
    php8.1-readline \
    php8.1-redis \
    php8.1-soap \
    php8.1-sqlite3 \
    php8.1-ssh2 \
    php8.1-xdebug \
    php8.1-xhprof \
    php8.1-xml \
    php8.1-xmlrpc \
    php8.1-zip

# Set a symlink to simplify the configuration, as we use a single php version
RUN ln -s /etc/php/8.1 /etc/php/current && \
    # Log to stdout
    sed -i 's/^error_log.*/error_log = \/proc\/self\/fd\/2/g' /etc/php/current/fpm/php-fpm.conf && \
    echo 'access.log = /proc/self/fd/2' >> /etc/php/current/fpm/php-fpm.conf && \
    # Create log dir
    mkdir /var/log/php && \
    # Install a few extensions with PECL instead of distro ones
    apt-get install -qq -y \
    build-essential \
    php-pear php8.1-dev pkg-config zlib1g-dev && \
    # Install extensions
    pecl channel-update pecl.php.net && \
    pecl -q install xhprof && \
    # Activate it
    echo "extension=xhprof.so" > /etc/php/current/mods-available/xhprof.ini && \
    phpenmod mongodb redis ssh2 xdebug xhprof && \
    # Clean
    apt-get purge -qq --autoremove -y \
    build-essential \
    php-pear php8.1-dev pkg-config zlib1g-dev && \
    apt-get autoremove -qq -y && \
    apt-get autoclean -qq && \
    apt-get clean -qq && \
    # Empty some directories from all files and hidden files
    rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
    find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete

# Copy custom php files
COPY ./common/php.cli.ini /etc/php/current/cli/conf.d/30-custom-php.ini
COPY ./common/php-fpm.ini /etc/php/current/fpm/conf.d/30-custom-php.ini
COPY ./common/php-fpm-www.conf /etc/php/current/fpm/pool.d/

# For custom Configuration that comes from outside (via a docker compose mount)
RUN mkdir /etc/php/current/fpm/user-conf.d && \
    echo "; Default empty file" > /etc/php/current/fpm/user-conf.d/example.conf && \
    # Create home for www-data
    mkdir /home/www-data && \
    chown www-data:www-data /home/www-data && \
    usermod -d /home/www-data www-data && \
    mkdir -p /run/php && \
    chown www-data:www-data /run/php

# Prepere entrypoint
COPY ./scripts/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data -u $WWWGROUP -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail

# Set working directory
WORKDIR /var/www

EXPOSE 9000

ENTRYPOINT  ["/docker-entrypoint.sh"]
