FROM ubuntu:22.04 AS php80

ARG DEBIAN_FRONTEND=noninteractive

ARG WWWGROUP=1000

# Set a default conf for apt-get install
# RUN echo 'apt::install-recommends "false";' > /etc/apt/apt.conf.d/no-install-recommends

# Install a few required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
    supervisor \
    curl \
    gnupg2 \
    software-properties-common && \
    add-apt-repository ppa:ondrej/php --yes 

# Update, upgrade
RUN apt-get update -qq -y && \
    apt-get upgrade -qq -y

# Packages
RUN apt-get install -qq -y \
    # Calling fpm locally
    libfcgi-bin \
    # Manipulate iptables rules (example: block smtps)
    iptables \
    # php8.0-cgi \
    # php8.0-dba \
    # php8.0-dev \
    # php8.0-enchant \
    # php8.0-phpdbg \
    # php8.0-pspell \
    # php8.0-recode \
    # php8.0-snmp \
    # php8.0-sybase \
    # php8.0-tidy \
    php8.0-apcu \
    php8.0-bcmath \
    php8.0-bz2 \
    php8.0-cli \
    php8.0-curl \
    php8.0-fpm \
    php8.0-gd \
    # php8.0-geoip \
    php8.0-gmp \
    php8.0-imagick \
    php8.0-imap \
    php8.0-interbase \
    php8.0-intl \
    # php8.0-json \
    php8.0-ldap \
    php8.0-mbstring \
    php8.0-mcrypt \
    php8.0-memcache \
    php8.0-memcached \
    php8.0-mongodb \
    php8.0-mysql \
    php8.0-odbc \
    php8.0-opcache \
    php8.0-pgsql \
    php8.0-readline \
    php8.0-redis \
    php8.0-soap \
    php8.0-sqlite3 \
    php8.0-ssh2 \
    php8.0-xdebug \
    php8.0-xhprof \
    php8.0-xml \
    php8.0-xmlrpc \
    php8.0-zip

# Set a symlink to simplify the configuration, as we use a single php version
RUN ln -s /etc/php/8.0 /etc/php/current && \
    # Log to stdout
    sed -i 's/^error_log.*/error_log = \/proc\/self\/fd\/2/g' /etc/php/current/fpm/php-fpm.conf && \
    echo 'access.log = /proc/self/fd/2' >> /etc/php/current/fpm/php-fpm.conf && \
    # Create log dir
    mkdir /var/log/php && \
    # Clean
    apt-get autoremove -qq -y && \
    apt-get autoclean -qq && \
    apt-get clean -qq && \
    # Empty some directories from all files and hidden files
    rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
    find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete

# Copy custom php files
COPY ./common/php.cli.ini /etc/php/current/cli/conf.d/30-custom-php.ini
COPY ./common/php-fpm.ini /etc/php/current/fpm/conf.d/30-custom-php.ini
COPY ./common/php-fpm.conf /etc/php/current/fpm/pool.d/

# For custom Configuration that comes from outside (via a docker compose mount)
RUN mkdir /etc/php/current/fpm/user-conf.d && \
    echo "; Default empty file" > /etc/php/current/fpm/user-conf.d/example.conf

# Create home for www-data
RUN mkdir /home/www-data && \
    chown www-data:www-data /home/www-data && \
    groupmod -g $WWWGROUP www-data && \
    usermod -u $WWWGROUP -d /home/www-data www-data && \
    mkdir -p /run/php && \
    chown www-data:www-data /run/php

# Prepere entrypoint
COPY ./scripts/docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

EXPOSE 9000

ENTRYPOINT  ["/entrypoint.sh"]
