FROM php:8.1-fpm as php81

# Arguments defined in docker-compose.yml
ARG WWWGROUP

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    supervisor \
    procps

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd sockets

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data -u $WWWGROUP -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail && \
    chmod 777 /home/$user
    
# Install redis
RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

# Install star-container
COPY ../builders/scripts/start-fpm-container.sh /start-container.sh
RUN chmod +x /start-fpm-container.sh

# Copy php config install
COPY ../builders/common/php.local.ini /usr/local/etc/php/conf.d/php.ini

# Set working directory
WORKDIR /var/www

EXPOSE 9000

USER sail

ENTRYPOINT  ["/start-container.sh"]
