FROM ubuntu:20.04 as node14

ARG WWWGROUP

# Set working directory
WORKDIR /var/www

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y \
        supervisor \
        curl \
        ca-certificates \
        zip \
        unzip \
        sqlite3 \
        python2 \
        dnsutils \
        librsvg2-bin

RUN curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh \
    && sh ./setup_14.sh

RUN apt-get update \
    && apt-get -y install nodejs

RUN npm install -g npm@9 \
    && npm install -g bun

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn

# Create system user to run Node Commands
RUN useradd -G www-data,root -u $WWWGROUP -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail && \
    chmod 777 /home/$user

USER sail
