FROM infortechms/infra-php:7.2-mssql-apache

ARG WWWGROUP

LABEL empresa="infortechms"
LABEL projeto="siafic.ms.gov.br"
LABEL imagem="convenio"

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq --no-install-recommends install supervisor;

# Prepere entrypoint
COPY ./scripts/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data -u $WWWGROUP -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail

# Set working directory
WORKDIR /var/www/html

ENTRYPOINT  ["/docker-entrypoint.sh"]
